version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "democratize-technology-code-developer"
      - "democratize-technology-code-reviewer"
    assignees:
      - "democratize-technology-code-developer"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"